"""
This is a setup.py script altered from one generated by py2applet

Usage:
    python setup_mac.py py2app -A

which will build an in-place, development version. It has yet to be tested
with a proper application bundle

"""

from setuptools import setup

# A custom plist for letting it associate with all files.
Plist = dict(CFBundleDocumentTypes= [dict(CFBundleTypeExtensions=["*"],
                                          #CFBundleTypeName="kUTTypeText", # this should be text files, but I'm not sure the details.
                                          CFBundleTypeRole="Editor"),
                                    ]
             )

APP = ['run.py']
DATA_FILES = ["peppy/icons"]
OPTIONS = {'argv_emulation': True, # this puts the names of dropped files into sys.argv when starting the app. 
           'iconfile': 'graphics/peppy.icns',
           'plist': Plist, 
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
