# peppy Copyright (c) 2006-2007 Rob McMullen
# Licenced under the GPL; see http://www.flipturn.org/peppy for more info
"""Graphviz DOT Language editing support.

L{Graphviz<http://graphviz.org/>} is a high quality open source
program to automatically layout directed and undirected graphs from a
text description of the node and edge relationships.  The description
language is called L{DOT<http://graphviz.org/doc/info/lang.html>} and
in most cases is generated by a program.  It is rare to write one by
hand, but when you have to, this mode is helpful.
"""

import os
import time

import wx

from peppy import *
from peppy.menu import *
from peppy.major import *


class ProgressBarTest(SelectAction):
    name = "&Test the progress bar"
    tooltip = "Test the progress bar"
    icon = wx.ART_FILE_OPEN

    def action(self, pos=-1):
        self.frame.statusbar.startProgress("Testing...", 100)
        for i in range(100):
            wx.Yield()
            self.frame.statusbar.updateProgress(i)
            time.sleep(.05)
        self.frame.statusbar.stopProgress()
        


class SandboxPlugin(MajorModeMatcherBase,debugmixin):
    """Plugin to register sandbox tests.
    """
    implements(IMenuItemProvider)

    default_menu=((None,None,Menu("Test").after("Minor Mode")),
                  (None,"Test",MenuItem(ProgressBarTest)),
                  )
    def getMenuItems(self):
        for mode,menu,item in self.default_menu:
            yield (mode,menu,item)

